import type { Store } from "./storeShape";

/**
 * One or two of every business record, linked the way the app links them.
 * The first record of each kind sets every optional field; the second, where
 * there is one, sets only the required ones. `q-1002` points at a drawing item
 * that does not exist, which the schema allows.
 */
export function sampleStore(): Store {
  return {
    files: [
      {
        id: "file-1001",
        fileName: "W9 2026.pdf",
        mimeType: "application/pdf",
        size: 3,
        storagePath: "uploads/file-1001.pdf",
        uploadedAt: "2026-09-01T12:00:00.000Z",
        purpose: "Supplier W9",
        linkedRecordType: "supplier",
        linkedRecordId: "sup-1001",
      },
      {
        id: "file-1002",
        fileName: "photo.JPG",
        mimeType: "image/jpeg",
        size: 3,
        storagePath: "uploads/file-1002.jpg",
        uploadedAt: "2026-09-02T08:30:00.000Z",
        purpose: "QC Photo",
      },
    ],
    suppliers: [
      {
        id: "sup-1001",
        recordState: "Active",
        voidReason: "Restored after review",
        name: "Legacy Paper",
        erpVendorId: "V-1001",
        status: "Approved",
        type: "Manufacturer",
        country: "United States",
        region: "TX",
        capableItems: ["Pallet", "Strapping"],
        primaryContact: "Ann Lee",
        email: "ann@example.com",
        phone: "555-0100",
        paymentTerms: "Net 30",
        hasW9: true,
        hasPaymentInfo: true,
        w9FileId: "file-1001",
        paymentInfoFileId: "file-1001",
        notes: "Preferred for pallets",
      },
      {
        id: "sup-1002",
        name: "UFP New Waverly",
        status: "Active",
        type: "Distributor",
        country: "United States",
        region: "",
        capableItems: [],
        primaryContact: "",
        email: "",
        phone: "",
        paymentTerms: "",
        hasW9: false,
        hasPaymentInfo: false,
        notes: "",
      },
    ],
    models: [
      { id: "model-1001", recordState: "Active", voidReason: "n/a", name: "BTA", productFamily: "Solar Module", status: "Active", notes: "Main line" },
      { id: "model-1002", name: "BTC 620", productFamily: "Solar Module", status: "Inactive", notes: "" },
    ],
    items: [
      {
        id: "item-1001",
        recordState: "Active",
        voidReason: "n/a",
        itemCode: "PAL-01",
        itemName: "Pallet",
        type: "Pallet",
        usedForModels: ["model-1001", "model-1002"],
        uom: "pcs",
        status: "Active",
      },
      { id: "item-1002", itemCode: "STR-01", itemName: "Strap", type: "Strapping", usedForModels: [], uom: "bundle", status: "Inactive" },
    ],
    drawingSets: [
      {
        id: "dwgset-1001",
        recordState: "Active",
        voidReason: "n/a",
        modelId: "model-1001",
        name: "BTA packaging",
        revision: "1.0",
        status: "Active",
        effectiveDate: "2026-01-15",
        maintainedBy: "Process Engineering",
        packageFileId: "file-1001",
        packageFileName: "W9 2026.pdf",
        drawingItems: [
          {
            id: "dwgitem-1001",
            itemId: "item-1001",
            revision: "1.0",
            status: "Active",
            drawingSource: "Item-specific PDF",
            fileName: "W9 2026.pdf",
            fileId: "file-1001",
          },
          { id: "dwgitem-1002", itemId: "item-1002", revision: "1.0", status: "Superseded", drawingSource: "Package PDF" },
        ],
      },
      {
        id: "dwgset-1002",
        modelId: "model-1002",
        name: "BTC packaging",
        revision: "1.0",
        status: "Draft",
        effectiveDate: "2026-03-01",
        maintainedBy: "Process Engineering",
        drawingItems: [],
      },
    ],
    projects: [
      {
        id: "proj-1001",
        recordState: "Active",
        voidReason: "n/a",
        name: "BTA packaging 2026",
        modelIds: ["model-1001"],
        drawingSetId: "dwgset-1001",
        type: "New Supplier Development",
        caseReason: "New Supplier Intro",
        status: "Quoting",
        supplierIds: ["sup-1001", "sup-1002"],
        itemIds: ["item-1001"],
        owner: "Purchasing",
        openDate: "2026-02-01",
        targetCloseDate: "2026-03-31",
      },
    ],
    quotes: [
      {
        id: "q-1001",
        recordState: "Active",
        voidReason: "n/a",
        supplierId: "sup-1001",
        projectId: "proj-1001",
        quoteType: "Case-linked",
        quoteReason: "New Quote",
        previousQuoteId: "q-1002",
        modelId: "model-1001",
        itemId: "item-1001",
        drawingSetId: "dwgset-1001",
        drawingItemId: "dwgitem-1001",
        quoteDate: "2026-02-10",
        effectiveFrom: "2026-02-10",
        effectiveTo: "2026-12-31",
        validUntil: "2026-03-10",
        currency: "USD",
        uom: "pcs",
        unitPrice: 12.3456,
        moq: "100",
        leadTime: "14 days",
        extraCostType: "Freight",
        extraCostAmount: 150.5,
        status: "Selected",
        attachmentFileId: "file-1001",
        notes: "Best price",
      },
      {
        id: "q-1002",
        supplierId: "sup-1001",
        quoteType: "Standalone",
        quoteReason: "New Quote",
        modelId: "model-1001",
        itemId: "item-1001",
        drawingSetId: "dwgset-1001",
        drawingItemId: "dwgitem-9999",
        quoteDate: "2026-01-20",
        effectiveFrom: "2026-01-20",
        currency: "USD",
        uom: "pcs",
        unitPrice: 12,
        moq: "100",
        leadTime: "3 weeks",
        extraCostType: "None",
        extraCostAmount: 0,
        status: "Received",
        notes: "",
      },
    ],
    quoteCaseLinks: [
      {
        id: "ql-1001",
        recordState: "Active",
        voidReason: "n/a",
        quoteId: "q-1001",
        projectId: "proj-1001",
        supplierId: "sup-1001",
        itemId: "item-1001",
        modelId: "model-1001",
        linkType: "Origin Case",
        sampleRequirement: "Required",
      },
    ],
    sourceAssignments: [
      {
        id: "assign-1001",
        recordState: "Active",
        voidReason: "n/a",
        projectId: "proj-1001",
        modelId: "model-1001",
        itemId: "item-1001",
        supplierId: "sup-1001",
        sourceQuoteId: "q-1001",
        role: "Primary",
        effectiveFrom: "2026-03-01",
        notes: "Primary source",
      },
    ],
    inspections: [
      {
        id: "ins-1001",
        recordState: "Active",
        voidReason: "n/a",
        supplierId: "sup-1001",
        projectId: "proj-1001",
        relatedQuoteId: "q-1001",
        modelId: "model-1001",
        drawingSetId: "dwgset-1001",
        itemId: "item-1001",
        drawingItemId: "dwgitem-1001",
        sampleRound: 2,
        sampleReceivedDate: "2026-02-20",
        inspectionDate: "2026-02-22",
        inspector: "QC Lead",
        result: "Pass",
        disposition: "Accepted",
        problemPhotos: 1,
        photoFileIds: ["file-1002"],
        notes: "Second round passed",
        signedDate: "2026-02-23",
      },
    ],
    incomingDefects: [
      {
        id: "def-1001",
        recordState: "Active",
        voidReason: "n/a",
        supplierId: "sup-1001",
        modelId: "model-1001",
        itemId: "item-1001",
        poNumber: "PO-1",
        poQty: 100,
        defectType: "Damage",
        defectDate: "2026-04-01",
        defectQty: 5,
        receivedQty: 95,
        defectAction: "Request Replacement",
        replacementQty: 5,
        replacementReceipts: [{ receivedDate: "2026-04-10", receivedQty: 5, result: "Accepted" }],
        actionCompleted: true,
        actionCompletedDate: "2026-04-10",
        materialReturned: true,
        returnDate: "2026-04-05",
        notes: "Forklift damage",
        photoFileIds: ["file-1002"],
        attachmentFileIds: ["file-1001"],
      },
      {
        id: "def-1002",
        supplierId: "sup-1002",
        itemId: "item-1001",
        defectType: "Other",
        defectDate: "2026-05-01",
        defectQty: 1,
        defectAction: "Request Credit",
        replacementReceipts: [],
        actionCompleted: true,
        materialReturned: false,
        notes: "",
        photoFileIds: [],
        attachmentFileIds: [],
      },
    ],
    purchasePrices: [
      {
        id: "po-1001",
        recordState: "Active",
        voidReason: "n/a",
        supplierId: "sup-1001",
        modelId: "model-1001",
        itemId: "item-1001",
        poNumber: "PO-1",
        orderDate: "2026-03-05",
        unitPrice: 12.25,
        quantity: 1000,
        currency: "USD",
        uom: "pcs",
        sourceType: "ERP Import",
        linkedQuoteId: "q-1001",
        buyer: "Purchasing",
        notes: "First order",
      },
    ],
    priceChanges: [
      {
        id: "pc-1001",
        recordState: "Active",
        voidReason: "n/a",
        supplierId: "sup-1001",
        modelId: "model-1001",
        itemId: "item-1001",
        sourceQuoteId: "q-1001",
        previousQuoteId: "q-1002",
        sourcePurchasePriceId: "po-1001",
        previousPurchasePriceId: "po-1001",
        sourceType: "Requote",
        oldPrice: 12,
        newPrice: 12.3456,
        currency: "USD",
        effectiveDate: "2026-02-10",
        reason: "Requote",
        status: "Pending",
      },
      {
        id: "pc-1002",
        supplierId: "sup-1002",
        modelId: "model-1002",
        itemId: "item-1002",
        sourceType: "Manual",
        oldPrice: 1,
        newPrice: 1.1,
        currency: "USD",
        effectiveDate: "2026-06-01",
        reason: "Other",
        status: "Approved",
      },
    ],
    scoreWeights: { sampleQuality: 30, incomingQuality: 20, pricing: 20, responsiveness: 10, scopeFit: 10, setup: 10 },
  };
}

/** Content for the sample store's files; each is 3 bytes, matching their recorded size. */
export function sampleFileContents(): Map<string, Buffer> {
  return new Map([
    ["file-1001", Buffer.from("pdf")],
    ["file-1002", Buffer.from("jpg")],
  ]);
}
